In [6]:
# Dependencies and Setup
import os
import csv
import pandas as pd
from sqlalchemy import create_engine

### Store CSV into DataFrame

In [7]:
# load and store dfs
citibike_2022_df = pd.concat(
    map(pd.read_csv, [
        'Resources/2022/JC-202201-citibike-tripdata.csv',
        'Resources/2022/JC-202202-citibike-tripdata.csv',
        'Resources/2022/JC-202203-citibike-tripdata.csv',
        'Resources/2022/JC-202204-citibike-tripdata.csv',
        'Resources/2022/JC-202205-citibike-tripdata.csv',
        'Resources/2022/JC-202206-citibike-tripdata.csv',
        'Resources/2022/JC-202207-citibike-tripdata.csv',
        'Resources/2022/JC-202208-citibike-tripdata.csv',
        'Resources/2022/JC-202209-citibike-tripdata.csv',
        'Resources/2022/JC-202210-citibike-tripdata.csv',
        'Resources/2022/JC-202211-citibike-tripdata.csv',
        'Resources/2022/JC-202212-citibike-tripdata.csv'
        ]), ignore_index=True)
# # output file path
# output_data_2022 = "./Resources/citibike_2022.csv"

citibike_2022_df.info()
citibike_2022_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 895485 entries, 0 to 895484
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             895485 non-null  object
 1   rideable_type       895485 non-null  object
 2   started_at          895485 non-null  object
 3   ended_at            895485 non-null  object
 4   start_station_name  895475 non-null  object
 5   start_station_id    895475 non-null  object
 6   end_station_name    892281 non-null  object
 7   end_station_id      892281 non-null  object
 8   start_lat           895485 non-null  float64
 9   start_lng           895485 non-null  float64
 10  end_lat             893515 non-null  float64
 11  end_lng             893515 non-null  float64
 12  member_casual       895485 non-null  object
dtypes: float64(4), object(9)
memory usage: 88.8+ MB

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,CA5837152804D4B5,electric_bike,2022-01-26 18:50:39,2022-01-26 18:51:53,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
1,BA06A5E45B6601D2,classic_bike,2022-01-28 13:14:07,2022-01-28 13:20:23,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
2,7B6827D7B9508D93,classic_bike,2022-01-10 19:55:13,2022-01-10 20:00:37,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
3,6E5864EA6FCEC90D,electric_bike,2022-01-26 07:54:57,2022-01-26 07:55:22,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
4,E24954255BBDE32D,electric_bike,2022-01-13 18:44:46,2022-01-13 18:45:43,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
895480,D438F1622839AC50,classic_bike,2022-12-06 15:43:38,2022-12-06 15:53:57,Dey St,JC065,Riverview Park,JC057,40.737828,-74.067083,40.744319,-74.043991,member
895481,747A63A8E782D171,electric_bike,2022-12-08 08:17:51,2022-12-08 08:23:33,9 St HBLR - Jackson St & 8 St,HB305,City Hall - Washington St & 1 St,HB105,40.747907,-74.038412,40.737360,-74.030970,casual
895482,AE090858CFDE6E82,electric_bike,2022-12-23 14:10:07,2022-12-23 14:14:18,Mama Johnson Field - 4 St & Jackson St,HB404,City Hall - Washington St & 1 St,HB105,40.743140,-74.040041,40.737360,-74.030970,member
895483,B3CC8E70AF4E259C,classic_bike,2022-12-02 04:43:25,2022-12-02 04:46:55,Mama Johnson Field - 4 St & Jackson St,HB404,City Hall - Washington St & 1 St,HB105,40.743135,-74.040080,40.737360,-74.030970,member
895484,176B601F21327350,classic_bike,2022-12-30 14:50:17,2022-12-30 14:55:37,14 St Ferry - 14 St & Shipyard Ln,HB202,City Hall - Washington St & 1 St,HB105,40.752747,-74.024035,40.737360,-74.030970,member

In [8]:
# rename columns
citibike_2022_df = citibike_2022_df.rename(columns = {
    'ride_id': 'ride id',
    'rideable_type': 'ride type', 
    'started_at': 'start at', 
    'ended_at': 'end at',
    'start_station_name': 'start station name', 
    'start_station_id': 'start station id', 
    'end_station_name': 'end station name',
    'end_station_id': 'end station id', 
    'start_lat': 'start latitude', 
    'start_lng': 'start longitude', 
    'end_lat': 'end latitude', 
    'end_lng': 'end longitude',
    'member_casual': 'membership'
})
citibike_2022_df.head()

,ride id,ride type,start at,end at,start station name,start station id,end station name,end station id,start latitude,start longitude,end latitude,end longitude,membership
0,CA5837152804D4B5,electric_bike,2022-01-26 18:50:39,2022-01-26 18:51:53,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
1,BA06A5E45B6601D2,classic_bike,2022-01-28 13:14:07,2022-01-28 13:20:23,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
2,7B6827D7B9508D93,classic_bike,2022-01-10 19:55:13,2022-01-10 20:00:37,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
3,6E5864EA6FCEC90D,electric_bike,2022-01-26 07:54:57,2022-01-26 07:55:22,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
4,E24954255BBDE32D,electric_bike,2022-01-13 18:44:46,2022-01-13 18:45:43,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member

In [9]:
#export to csv
citibike_2022_df.to_csv("./Resources/citibike_2022.csv", index = False)

In [19]:
# load and store dfs
citibike_2021_df = pd.concat(
    map(pd.read_csv, [
        'Resources/2021/JC-202101-citibike-tripdata.csv',
        'Resources/2021/JC-202102-citibike-tripdata.csv',
        'Resources/2021/JC-202103-citibike-tripdata.csv',
        'Resources/2021/JC-202104-citibike-tripdata.csv',
        'Resources/2021/JC-202105-citibike-tripdata.csv',
        'Resources/2021/JC-202106-citibike-tripdata.csv',
        'Resources/2021/JC-202107-citibike-tripdata.csv',
        'Resources/2021/JC-202108-citibike-tripdata.csv',
        'Resources/2021/JC-202109-citibike-tripdata.csv',
        'Resources/2021/JC-202110-citibike-tripdata.csv',
        'Resources/2021/JC-202111-citibike-tripdata.csv',
        'Resources/2021/JC-202112-citibike-tripdata.csv'
        ]), ignore_index=True)
# output file path
output_data_2021 = "./Resources/citibike_2021.csv"
# #export to csv
# citibike_2021_df.to_csv("./Resources/citibike_2021.csv", index = False)

citibike_2021_df.info()
citibike_2021_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 644443 entries, 0 to 644442
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   trip_duration       11624 non-null   float64
 1   started_at          644443 non-null  object
 2   ended_at            644443 non-null  object
 3   start_station_id    644443 non-null  object
 4   start_station_name  644443 non-null  object
 5   start_lat           644443 non-null  float64
 6   start_lng           644443 non-null  float64
 7   end_station_id      640943 non-null  object
 8   end_station_name    640943 non-null  object
 9   end_lat             642211 non-null  float64
 10  end_lng             642211 non-null  float64
 11  bike_id             11624 non-null   float64
 12  member_casual       644443 non-null  object
 13  birth_year          11624 non-null   float64
 14  gender              11624 non-null   float64
 15  ride_id             632819 non-null  object
 16  rideable_type       632819 non-null  object
dtypes: float64(8), object(9)
memory usage: 83.6+ MB

,trip_duration,started_at,ended_at,start_station_id,start_station_name,start_lat,start_lng,end_station_id,end_station_name,end_lat,end_lng,bike_id,member_casual,birth_year,gender,ride_id,rideable_type
0,266.0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494.0,Subscriber,1988.0,1.0,NaN,NaN
1,1543.0,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,45343.0,Customer,1996.0,2.0,NaN,NaN
2,1461.0,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,31794.0,Customer,1995.0,1.0,NaN,NaN
3,793.0,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,42316.0,Customer,1969.0,0.0,NaN,NaN
4,596.0,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,32575.0,Customer,1969.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644438,NaN,2021-12-16 17:17:46,2021-12-16 17:22:53,JC005,Grove St PATH,40.719586,-74.043117,JC009,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,13FE513C650901A3,classic_bike
644439,NaN,2021-12-07 17:10:29,2021-12-07 17:15:02,JC005,Grove St PATH,40.719586,-74.043117,JC009,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,CA29051F38E67D30,classic_bike
644440,NaN,2021-12-18 09:50:14,2021-12-18 09:55:55,JC005,Grove St PATH,40.719586,-74.043117,JC009,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,A719DEA143005404,classic_bike
644441,NaN,2021-12-10 21:43:32,2021-12-10 21:49:04,JC005,Grove St PATH,40.719586,-74.043117,JC009,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,D39126975208B59D,classic_bike
644442,NaN,2021-12-08 11:09:56,2021-12-08 11:14:58,JC019,Hilltop,40.731169,-74.057574,JC009,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,1BB5CF43B5DF7E05,classic_bike

In [32]:
citibike_2021_df = citibike_2021_df.rename(columns = {
    'trip_duration': 'trip duration', 
    'started_at': 'start at', 
    'ended_at': 'end at', 
    'start_station_id': 'start station id',
    'start_station_name': 'start station name', 
    'start_lat': 'start latitude', 
    'start_lng': 'start longitude', 
    'end_station_id': 'end station id',
    'end_station_name': 'end station name', 
    'end_lat': 'end latitude', 
    'end_lng': 'end longitude', 
    'bike_id': 'bike id', 
    'member_casual': 'membership',
    'birth_year': 'birth year', 
    'gender': 'gender', 
    'ride_id': 'ride id', 
    'rideable_type': 'ride type'
    })
citibike_2021_df = citibike_2021_df.replace({
    'Customer': 'casual',
    'Subscriber': 'member'
})
citibike_2021_df['ride type'] = citibike_2021_df['ride type'].fillna('docked_bike')
citibike_2021_df

,trip duration,start at,end at,start station id,start station name,start latitude,start longitude,end station id,end station name,end latitude,end longitude,bike id,membership,birth year,gender,ride id,ride type
0,266.0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494.0,member,1988.0,1.0,NaN,docked_bike
1,1543.0,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,45343.0,casual,1996.0,2.0,NaN,docked_bike
2,1461.0,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,31794.0,casual,1995.0,1.0,NaN,docked_bike
3,793.0,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,42316.0,casual,1969.0,0.0,NaN,docked_bike
4,596.0,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,32575.0,casual,1969.0,0.0,NaN,docked_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644438,NaN,2021-12-16 17:17:46,2021-12-16 17:22:53,JC005,Grove St PATH,40.719586,-74.043117,JC009,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,13FE513C650901A3,classic_bike
644439,NaN,2021-12-07 17:10:29,2021-12-07 17:15:02,JC005,Grove St PATH,40.719586,-74.043117,JC009,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,CA29051F38E67D30,classic_bike
644440,NaN,2021-12-18 09:50:14,2021-12-18 09:55:55,JC005,Grove St PATH,40.719586,-74.043117,JC009,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,A719DEA143005404,classic_bike
644441,NaN,2021-12-10 21:43:32,2021-12-10 21:49:04,JC005,Grove St PATH,40.719586,-74.043117,JC009,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,D39126975208B59D,classic_bike
644442,NaN,2021-12-08 11:09:56,2021-12-08 11:14:58,JC019,Hilltop,40.731169,-74.057574,JC009,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,1BB5CF43B5DF7E05,classic_bike

In [33]:
#export to csv
citibike_2021_df.to_csv("./Resources/citibike_2021.csv", index = False)

In [34]:
# stack 2021 csv on top of 2022 csv
citibike_2122_df = pd.concat(
    map(pd.read_csv, [
        './Resources/citibike_2021.csv',
        './Resources/citibike_2022.csv'
        ]), ignore_index=True)
# output file path
output_data_2122 = "./Resources/citibike_2122.csv"

citibike_2122_df.info()
citibike_2122_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1539928 entries, 0 to 1539927
Data columns (total 17 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   trip duration       11624 non-null    float64
 1   start at            1539928 non-null  object
 2   end at              1539928 non-null  object
 3   start station id    1539918 non-null  object
 4   start station name  1539918 non-null  object
 5   start latitude      1539928 non-null  float64
 6   start longitude     1539928 non-null  float64
 7   end station id      1533224 non-null  object
 8   end station name    1533224 non-null  object
 9   end latitude        1535726 non-null  float64
 10  end longitude       1535726 non-null  float64
 11  bike id             11624 non-null    float64
 12  membership          1539928 non-null  object
 13  birth year          11624 non-null    float64
 14  gender              11624 non-null    float64
 15  ride id             1528304 non-null  object
 16  ride type           1539928 non-null  object
dtypes: float64(8), object(9)
memory usage: 199.7+ MB

,trip duration,start at,end at,start station id,start station name,start latitude,start longitude,end station id,end station name,end latitude,end longitude,bike id,membership,birth year,gender,ride id,ride type
0,266.0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494.0,member,1988.0,1.0,NaN,docked_bike
1,1543.0,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,45343.0,casual,1996.0,2.0,NaN,docked_bike
2,1461.0,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,31794.0,casual,1995.0,1.0,NaN,docked_bike
3,793.0,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,42316.0,casual,1969.0,0.0,NaN,docked_bike
4,596.0,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,32575.0,casual,1969.0,0.0,NaN,docked_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1539923,NaN,2022-12-06 15:43:38,2022-12-06 15:53:57,JC065,Dey St,40.737828,-74.067083,JC057,Riverview Park,40.744319,-74.043991,NaN,member,NaN,NaN,D438F1622839AC50,classic_bike
1539924,NaN,2022-12-08 08:17:51,2022-12-08 08:23:33,HB305,9 St HBLR - Jackson St & 8 St,40.747907,-74.038412,HB105,City Hall - Washington St & 1 St,40.737360,-74.030970,NaN,casual,NaN,NaN,747A63A8E782D171,electric_bike
1539925,NaN,2022-12-23 14:10:07,2022-12-23 14:14:18,HB404,Mama Johnson Field - 4 St & Jackson St,40.743140,-74.040041,HB105,City Hall - Washington St & 1 St,40.737360,-74.030970,NaN,member,NaN,NaN,AE090858CFDE6E82,electric_bike
1539926,NaN,2022-12-02 04:43:25,2022-12-02 04:46:55,HB404,Mama Johnson Field - 4 St & Jackson St,40.743135,-74.040080,HB105,City Hall - Washington St & 1 St,40.737360,-74.030970,NaN,member,NaN,NaN,B3CC8E70AF4E259C,classic_bike
1539927,NaN,2022-12-30 14:50:17,2022-12-30 14:55:37,HB202,14 St Ferry - 14 St & Shipyard Ln,40.752747,-74.024035,HB105,City Hall - Washington St & 1 St,40.737360,-74.030970,NaN,member,NaN,NaN,176B601F21327350,classic_bike

In [35]:
# fill NaN values with 0
citibike_2122_df = citibike_2122_df.fillna(0)
# change dtypes to integer
citibike_2122_df.astype({
    'bike id': 'int64',
    'birth year': 'int64',
    'gender': 'int64'    
    }).dtypes

trip duration         float64
start at               object
end at                 object
start station id       object
start station name     object
start latitude        float64
start longitude       float64
end station id         object
end station name       object
end latitude          float64
end longitude         float64
bike id                 int64
membership             object
birth year              int64
gender                  int64
ride id                object
ride type              object
dtype: object

In [36]:
#export to csv
citibike_2122_df.to_csv("./Resources/citibike_2122.csv", index = False)